### ISSUE TITLE
Register angular-validation on ngmodules.com

### ISSUE THREAD

**Issue by juanchavezlive** [ghiscoding/angular-validation#17]
In order to spread the word about this angular component, i suggest to register the module in ngmodules.org (One of the best sources of information in order to search Angular modules).

**Comment by juanchavezlive** [comment]
![1](https://cloud.githubusercontent.com/assets/5005394/6901169/bdba7bae-d6c8-11e4-90f0-84a732c132ec.png)

Done :)

**Comment by ghiscoding** [comment]
Ok thanks the information looks good, except maybe the naming is different compare to my bower call but it's not major. I was actually thinking to rename my own bower to have the same name as you actually did... thinking more and more about changing my bower name.

Just a side note though, if there is any other sites that I should know of, I would rather post it myself next time so that the owner name can show up as my name... but don't worry, it's ok for this one ;)

Happy to know you use it and like it... thanks again for the Spanish version :)

**Comment by ghiscoding** [comment]
So I ended up creating another bower with the same naming as you did, both bower options are working (ghiscoding.angular-validation  OR angular-validation-ghiscoding). The readme was updated to reflect this.

**Comment by juanchavezlive** [comment]
I have just remove it. Now you can publish it again ;)

**Comment by ghiscoding** [comment]
It was not removed, since it said that the name was already taken and when searching for it, it still showed up with your name. But please leave it as it is, it is fine like that :)
I just took your post and added some tags, it looks good now. Thanks :)

As for your code, I added Spanish option on the main page of my sample code (also on plunker) it's nice to see all these new languages coming in :)
